// ============================================
// STATIC BUILD — the game as plain files in dist/, for static hosts such as Vercel.
//
// A static host cannot run the Node server, so multiplayer, the leaderboard and
// the admin panel talk to a separately hosted server (e.g. on Render), whose
// address comes from UNEARTH_SERVER_URL. Without it, solo play, the Daily Dig and
// the Archive still work; online features report that the server is unreachable.
//
//   UNEARTH_SERVER_URL=https://unearth.onrender.com npm run build:static
// ============================================

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'fs';
import { dirname, join, relative, resolve } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const THREE = join(ROOT, 'node_modules', 'three');
const SERVER_URL = (process.env.UNEARTH_SERVER_URL || '').trim().replace(/\/+$/, '');
const PUBLIC_URL = (process.env.PUBLIC_URL || 'https://www.playunearth.tech').trim().replace(/\/+$/, '');

if (SERVER_URL && !/^https?:\/\/[^/]+$/i.test(SERVER_URL)) {
    console.error(`UNEARTH_SERVER_URL must be an origin such as https://unearth.onrender.com (got "${SERVER_URL}")`);
    process.exit(1);
}
if (!existsSync(THREE)) {
    console.error('three is not installed; run npm install first.');
    process.exit(1);
}

rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

// Game client at the site root, media and the admin panel under /public
cpSync(join(ROOT, 'client'), DIST, { recursive: true });
cpSync(join(ROOT, 'public'), join(DIST, 'public'), { recursive: true });

// three.js: the core module plus the add-ons the game imports, with their relative imports
const vendor = join(DIST, 'vendor', 'three');
mkdirSync(join(vendor, 'build'), { recursive: true });
cpSync(join(THREE, 'build', 'three.module.js'), join(vendor, 'build', 'three.module.js'));

const addons = new Set();
const queue = [];
const sourceFiles = [];
(function walk(dir) {
    for (const name of readdirSafe(dir)) {
        const p = join(dir, name);
        if (name.endsWith('.js')) sourceFiles.push(p);
        else if (!name.includes('.')) walk(p);
    }
})(join(ROOT, 'client', 'js'));
for (const file of sourceFiles) {
    for (const m of readFileSync(file, 'utf8').matchAll(/['"]three\/addons\/([^'"]+)['"]/g)) queue.push(join(THREE, 'examples', 'jsm', m[1]));
}
while (queue.length) {
    const file = queue.pop();
    if (addons.has(file)) continue;
    if (!existsSync(file)) { console.error(`Missing three.js add-on: ${relative(THREE, file)}`); process.exit(1); }
    addons.add(file);
    for (const m of readFileSync(file, 'utf8').matchAll(/(?:from|import)\s*['"](\.{1,2}\/[^'"]+)['"]/g)) queue.push(resolve(dirname(file), m[1]));
}
for (const file of addons) {
    const out = join(vendor, relative(THREE, file));
    mkdirSync(dirname(out), { recursive: true });
    cpSync(file, out);
}

// Server address for the client and the admin panel
writeFileSync(join(DIST, 'config.js'),
    `// Generated by scripts/build-static.mjs\nwindow.UNEARTH_SERVER = window.UNEARTH_SERVER || ${JSON.stringify(SERVER_URL)};\n`);

// Crawler files (served by the Node server on other hosts)
writeFileSync(join(DIST, 'robots.txt'),
    `User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /public/admin/\n\nSitemap: ${PUBLIC_URL}/sitemap.xml\n`);
writeFileSync(join(DIST, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `  <url><loc>${PUBLIC_URL}/</loc><lastmod>${new Date().toISOString().slice(0, 10)}</lastmod><changefreq>weekly</changefreq><priority>1.0</priority></url>\n</urlset>\n`);

console.log(`Static build written to dist/ (${addons.size} three.js add-on files).`);
console.log(SERVER_URL
    ? `Online features use ${SERVER_URL}`
    : 'UNEARTH_SERVER_URL is not set: multiplayer, leaderboard and admin will be unavailable on this deployment.');

function readdirSafe(dir) {
    try { return readdirSync(dir); } catch { return []; }
}
